apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: node-app-server-postgres-password
  namespace: the-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: the-dev-dev/the-dev/POSTGRES_PASSWORD
